# ✅ Full cloudbuild.yaml: Secure Build → Scan → Push → Deploy with Fixed Grype Execution

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _TAG: 'latest'

steps:
# === BACKEND ===
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Backend Image'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend:${_TAG}', './backend']

- name: 'aquasec/trivy:latest'
  id: 'Trivy Scan Backend'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      trivy image --exit-code 0 --format json -o trivy-backend-report.json us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend:${_TAG}

- name: 'gcr.io/cloud-builders/bash'
  id: 'Grype Scan Backend'
  args:
    - '-c'
    - |
      curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      grype us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend:${_TAG} -o json > grype-backend-report.json

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Backend Image'
  args: ['push', 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend:${_TAG}']

# === FRONTEND ===
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Frontend Image'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-frontend:${_TAG}', './frontend']

- name: 'aquasec/trivy:latest'
  id: 'Trivy Scan Frontend'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      trivy image --exit-code 0 --format json -o trivy-frontend-report.json us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-frontend:${_TAG}

- name: 'gcr.io/cloud-builders/bash'
  id: 'Grype Scan Frontend'
  args:
    - '-c'
    - |
      curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      grype us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-frontend:${_TAG} -o json > grype-frontend-report.json

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Frontend Image'
  args: ['push', 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-frontend:${_TAG}']

# === UPLOAD REPORTS TO GCS ===
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Upload Reports to GCS'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      gsutil cp *.json gs://secure-scan-reports-file

# === DEPLOY TO GKE ===
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy to GKE'
  args:
    - 'apply'
    - '-f'
    - 'k8s/'
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
  - 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend:${_TAG}'
  - 'us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-frontend:${_TAG}'

