version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # HostPort:ContainerPort
    depends_on:
      - backend
    networks:
      - app-net
    restart: unless-stopped

    # Security enhancements
    read_only: true
    security_opt:
      - no-new-privileges:true

    # Optional: Only if NGINX supports non-root
    # user: "1000:1000"

    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx
      - /var/tmp

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"  # Expose backend on different host port
    networks:
      - app-net
    restart: unless-stopped

    # Security enhancements
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"

    tmpfs:
      - /tmp

networks:
  app-net:
    driver: bridge

