apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-backend
  template:
    metadata:
      labels:
        app: secure-backend
    spec:
      containers:
      - name: secure-backend
        image: us-central1-docker.pkg.dev/zinc-hour-459818-m2/secure-app-repo/secure-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: secure-backend-service
spec:
  selector:
    app: secure-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

